{"title": "Joe Louis Arena Becomes First Professional Sports Facility in Nation  to Attain Safety and Security Designation", "link": "http://news.usm.edu/article/joe-louis-arena-becomes-first-professional-sports-facility-nation-attain-safety-and-security", "date": "06/30/2016"}
{"title": "National Intercollegiate Athletics Safety and Security Summit Jan. 24-26", "link": "http://news.usm.edu/article/national-intercollegiate-athletics-safety-and-security-summit-jan-24-26", "date": "12/13/2016"}
{"title": "First-ever Sports Safety and Security Radiological Response Exercise Conducted in Mississippi held at USM Jan. 18", "link": "http://news.usm.edu/article/first-ever-sports-safety-and-security-radiological-response-exercise-conducted-mississippi-h", "date": "01/19/2017"}
{"title": "National Interscholastic Summit Addresses School Safety and Security Issues", "link": "http://news.usm.edu/article/national-interscholastic-summit-addresses-school-safety-and-security-issues", "date": "03/29/2017"}
{"title": "Building Resiliency Focus of National Sports Safety and Security Conference ", "link": "http://news.usm.edu/article/building-resiliency-focus-national-sports-safety-and-security-conference", "date": "04/24/2017"}
{"title": "Professionals to Receive Recognition during National Sports Security Conference", "link": "http://news.usm.edu/article/professionals-receive-recognition-during-national-sports-security-conference-1", "date": "06/14/2017"}
{"title": "Russ Simons Receives Distinguished Leadership Award at National Sports Safety and Security Conference", "link": "http://news.usm.edu/article/russ-simons-receives-distinguished-leadership-award-national-sports-safety-and-security-conf", "date": "06/28/2017"}
{"title": "NCS4 Releases Current Safety and Security Best Practices ", "link": "http://news.usm.edu/article/ncs4-releases-current-safety-and-security-best-practices", "date": "08/03/2017"}
{"title": "NFL\u2019s Senior Vice President of Security Keynotes NCS4 Summit", "link": "http://news.usm.edu/article/nfl-s-senior-vice-president-security-keynotes-ncs4-summit", "date": "01/19/2018"}
{"title": "Professionals to Receive Recognition during National Sports Security Conference", "link": "http://news.usm.edu/article/professionals-receive-recognition-during-national-sports-security-conference-0", "date": "06/02/2016"}
